### ISSUE TITLE
sudo: unable to open /etc/sudoers: Permission denie

### ISSUE THREAD

**Issue by pedrodeleon55** [olivedapp/chaturbate-live-recorder#5]
olived-web  | sudo: unable to open /etc/sudoers: Permission denied
olived-web  | sudo: no valid sudoers sources found, quitting
olived-web  | sudo: error initializing audit plugin sudoers_audit
olived-web  | Error: Failed to write machine-id
olived-web exited with code 1

This is ll I get when running the docker compose, however I have no problem accessing this file  with my user or the root, have tried running with both, same issue.

**Comment by olivedbot** [comment]
```yaml
services:
  olived-web:
    container_name: olived-web
    image: olivedapp/olived-web:latest
    pull_policy: always
    environment:
      - PUID=1000
      - PGID=1000
    ports: 
      - "9843:9843"
    volumes:
      - $PWD/olivedpro_downloads:/olivedapp/olivedpro_downloads
      - $PWD/.olivedpro:/olivedapp/.olivedpro
```

You need to change PUID and PGID to yours.
In this instance PUID=1000 and PGID=1000, to find yours use id your_user as below:
```sh
id your_user
```

Example output:
```sh
uid=1000(your_user) gid=1000(your_user) groups=1000(your_user)
```
